set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER clang-19 CACHE STRING "")
set(CMAKE_CXX_COMPILER clang++-19 CACHE STRING "")
set(CMAKE_ASM_COMPILER clang-19 CACHE STRING "")

set(CMAKE_C_COMPILER_TARGET x86_64-unknown-none-elf CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET x86_64-unknown-none-elf CACHE STRING "")
set(CMAKE_ASM_COMPILER_TARGET x86_64-unknown-none-elf CACHE STRING "")

set(CMAKE_AR ar CACHE STRING "")
set(CMAKE_RANLIB ranlib CACHE STRING "")
set(CMAKE_LINKER ld.lld-19 CACHE STRING "")
set(CMAKE_CXX_LINK_EXECUTABLE
    "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
    CACHE STRING ""
)
